package com.example.fitness_app.constrants;

public class EventBusEvents {
    public static final String EVENT_BUS_EVENT_TASK_ENTRY_DELETED = "EVENT_BUS_EVENT_TASK_ENTRY_DELETED";
    public static final String EVENT_BUS_EVENT_TASK_ENTRY_ADDED = "EVENT_BUS_EVENT_TASK_ENTRY_ADDED";
    public static final String EVENT_BUS_EVENT_TASK_EDITED = "EVENT_BUS_EVENT_TASK_EDITED";
    public static final String EVENT_BUS_EVENT_TASK_DELETED = "EVENT_BUS_EVENT_TASK_DELETED";
    public static final String EVENT_BUS_EVENT_TASK_ENTRY_ADDED_CURRENT_DAY = "EVENT_BUS_EVENT_TASK_ENTRY_ADDED_CURRENT_DAY";
    public static final String EVENT_BUS_EVENT_ACHIEVEMENT_DELETED = "EVENT_BUS_EVENT_ACHIEVEMENT_DELETED";
    public static final String EVENT_BUS_EVENT_ACHIEVEMENT_ADDED = "EVENT_BUS_EVENT_ACHIEVEMENT_ADDED";
    public static final String EVENT_BUS_EVENT_ACHIEVEMENT_REQUEST_APPROVED = "EVENT_BUS_EVENT_ACHIEVEMENT_REQUEST_APPROVED";
    public static final String EVENT_BUS_EVENT_ACHIEVEMENT_REQUEST_DECLINED = "EVENT_BUS_EVENT_ACHIEVEMENT_REQUEST_DECLINED";
    public static final String EVENT_BUS_EVENT_MEASUREMENT_ADDED = "EVENT_BUS_EVENT_MEASUREMENT_ADDED";
    public static final String EVENT_BUS_EVENT_MEASUREMENT_UPDATED = "EVENT_BUS_EVENT_MEASUREMENT_UPDATED";
    public static final String EVENT_BUS_EVENT_MEASUREMENT_DELETED = "EVENT_BUS_EVENT_MEASUREMENT_DELETED";
    public static final String EVENT_BUS_EVENT_QUEST_ADDED = "EVENT_BUS_EVENT_QUEST_ADDED";
    public static final String EVENT_BUS_EVENT_QUEST_DELETED = "EVENT_BUS_EVENT_QUEST_DELETED";
    public static final String EVENT_BUS_EVENT_QUEST_REQUEST_APPROVED = "EVENT_BUS_EVENT_QUEST_REQUEST_APPROVED";
    public static final String EVENT_BUS_EVENT_QUEST_REQUEST_DECLINED = "EVENT_BUS_EVENT_QUEST_REQUEST_DECLINED";
}
